name: umcs-cd-pipeline
description: cd pipeline for umcs api

on:
  push: 
    branches: [ master ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git
        uses: actions/checkout@v6.0.2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.1.0
        with: 
          dotnet-version: |
            8.0.x
            9.0.x
      
      - name: Restore dependencies
        run: dotnet restore Server.sln

      - name: Build
        run: dotnet build Server.sln --configuration Release --no-restore
      
      - name: Test
        run: dotnet test Server.sln --configuration Release --no-restore --no-build --verbosity normal
        continue-on-error: true # Continue even if no tests were found
      
      - name: Publish
        run: dotnet publish Server.Api/Server.Api.csproj --configuration Release --output ${{ env.DOTNET_ROOT }}/api --no-restore --no-build
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: api-artifact
          path: ${{ env.DOTNET_ROOT }}/api
      
  check-artifact-status:
    runs-on: ubuntu-latest
    needs: builds

    steps:
      - name: Attempt to download artifact
        id: download-artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: api-artifact
        continue-on-error: true
      
      - name: Check if artifact exists (Check if download succeeded)
        if: steps.download-artifact.outcome == 'success'
        run: echo "Artifact downloaded."
      
      - name: check if artifact not exists
        if: steps.download-artifact.outcome == 'failure'
        run: echo "Artifact not found."
  
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    needs: builds

    environment: 
      name: Dev
      url: ${{ steps.deploy.outputs.webapp-url }}/swagger/index.html

    # ${{ needs.builds-and-deploy-dev.outputs.webapp-url }}
    outputs:
      webapp-url: ${{ steps.deploy.outputs.webapp-url }}/swagger/index.html

    steps:
      - name: Download a Build Artifact
        id: download-artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: api-artifact
          path: ./deploy-webapp
      
      - name: Azure WebApp
        id: deploy
        uses: Azure/webapps-deploy@v3.0.6
        with:
          app-name: umcs-api-dev
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
          package: ./deploy-webapp

      - name: Show deployed URL
        run: | 
          echo "Deployed to: ${{ steps.deploy.outputs.webapp-url }}/swagger/index.html"

  build-and-deploy-prod:
    runs-on: ubuntu-latest
    needs: build-and-deploy-dev

    environment:
      name: Prod
      url: ${{ steps.deploy.outputs.webapp-url }}/swagger/index.html

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: api-artifact
          path: ./deploy-webapp
      
      - name: Azure Webapp
        id: deploy
        uses: Azure/webapps-deploy@v3.0.6
        with:
          app-name: umcs-api-prod
          publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
          package: ./deploy-webapp
      
      - name: Show deployed URL
        run: |
          echo "Deployed to prod: ${{ steps.deploy.outputs.webapp-url }}/swagger/index.html"
